### ISSUE TITLE
Security issue for postcss

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-rest-client-angular#109]
Need to fix the [postcss security issue](https://github.com/OpenLiberty/guide-rest-client-angular/security/dependabot/finish/src/main/frontend/package-lock.json/postcss/open)

**Comment by realModusOperandi** [comment]
Will deliver into branch `version-update`

**Comment by gkwan-ibm** [comment]
close
- the security issue was fixed
