### ISSUE TITLE
Navigating to http://localhost:9080/app  after server is started shows nothing on MacOS BigSur

### ISSUE THREAD

**Issue by dbnex14** [OpenLiberty/guide-rest-client-angular#119]
On Macbook Pro with MacOS BigSur, following your instructions and after running `mvn liberty:run`, server successfully started without any errors.  However, navigating to http://localhost:9080/app does nothing.  It ends up in endless reload icon spinning in browser and nothing shows.

Here is output after server successfully started:
```
[INFO] Launching defaultServer (Open Liberty 21.0.0.8/wlp-1.0.55.cl210820210727-1323) on OpenJDK 64-Bit Server VM, version 15.0.1+9 (en_CA)
[INFO] [AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[INFO] [AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
[INFO] [AUDIT   ] CWWKT0016I: Web application available (default_host): http://192.168.1.73:9080/
[INFO] [AUDIT   ] CWWKZ0001I: Application guide-rest-client-angular started in 0.337 seconds.
**[INFO] [ERROR   ] CWWKO0221E: TCP Channel defaultHttpEndpoint initialization did not succeed.  The socket bind did not succeed for host * and port 9080.  The port might already be in use.  Exception Message: Address already in use**
[INFO] [AUDIT   ] CWWKT0017I: Web application removed (default_host): http://192.168.1.73:9080/
[INFO] [AUDIT   ] CWWKF0012I: The server installed the following features: [jaxrs-2.1, jaxrsClient-2.1, jsonp-1.1, servlet-4.0].
[INFO] [AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 2.164 seconds.
```
After killing the process that was using port 9080 (kill -9 :9080) and reissuing mvn liberty:run, get error:[INFO] 
```
CWWKE0005E: The runtime environment could not be launched.
[INFO] CWWKE0029E: An instance of server defaultServer is already running.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  32.111 s
[INFO] Finished at: 2021-08-31T09:37:21-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.openliberty.tools:liberty-maven-plugin:3.3.4:run (default-cli) on project guide-rest-client-angular: CWWKM2002E: Failed to invoke [/Users/dinob/Desktop/angular-openliberty/guide-rest-client-angular/finish/target/liberty/wlp/bin/server, run, defaultServer]. RC= 1 but expected=0. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by gkwan-ibm** [comment]
hi @dbnex14 

In your first batch of logs, there was an error. It means that the port 9080 was used by other process. The server could not be started correctly. That's why nothing show when navigating to http://localhost:9080/app .

```
**[INFO] [ERROR   ] CWWKO0221E: TCP Channel defaultHttpEndpoint initialization did not succeed.  The socket bind did not succeed for host * and port 9080.  The port might already be in use.  Exception Message: Address already in use**
```

I doubt the command `kill -9 :9080` can kill the required process.

To stop the `liberty:run` session, you can simply press `CTRL+C` or open another command session, change to the directory where you ran `mvn liberty:run`, run `mvn liberty:stop` to stop. 

Suggest close the process which is using port 9080 and retry. Run `lsof -i TCP:9080` to see which process is using 9080.

**Comment by dbnex14** [comment]
> hi @dbnex14
> 
> In your first batch of logs, there was an error. It means that the port 9080 was used by other process. The server could not be started correctly. That's why nothing show when navigating to http://localhost:9080/app .
> 
> ```
> **[INFO] [ERROR   ] CWWKO0221E: TCP Channel defaultHttpEndpoint initialization did not succeed.  The socket bind did not succeed for host * and port 9080.  The port might already be in use.  Exception Message: Address already in use**
> ```
> 
> I doubt the command `kill -9 :9080` can kill the required process.
> 
> To stop the `liberty:run` session, you can simply press `CTRL+C` or open another command session, change to the directory where you ran `mvn liberty:run`, run `mvn liberty:stop` to stop.
> 
> Suggest close the process which is using port 9080 and retry. Run `lsof -i TCP:9080` to see which process is using 9080.

I cannot explain how I got into this state but I did try to kill it with CTRL+C first and it appeared to have terminated it but it did not, that is how I ended up using kill -9 :9080 which I think created additional issues that I managed only to resolve by reboot and fresh clone of the repo.
Thank you
