### ISSUE TITLE
Pre-publishing tasks

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guide-rest-client-angular#29]
Pre-Publishing Tests

- [x] Check appearance (contents, headings, paragraphs, code snippets, outputs, links, hotspots) of the guide on test site, ie, qa-guides
- [x] Read through the guide 
- [x] Clone repo and test start directory with no error
- [x] Run `diff -r start/ finish/` 
- [x] Follow the instruction in the guide to test that it is working
- Use the `copy` buttons instead of typing 
- [x] Check that the release date on the readme.adoc is the publishing date

**Comment by DannyS03** [comment]
LGTM

**Comment by evelinec** [comment]
Thank you @DannyS03. Can you close this issue?
