### ISSUE TITLE
Post-Publishing Tests

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guide-rest-client-angular#31]
Post-Publishing Tests (Nimrah)

- [x] Check appearance (contents, headings, paragraphs, code snippets, outputs, links) of the guide on openliberty.io
- [x] Clone repo and test finish directory with no error

Other post-publishing tasks (to be done by the Admin Team) (Eveline)

- [x] Add description for the repo with link to guide's published website
- [x] Double check the SEO title and description are added for the guide
- [x] Ensure automated test for PR and Continuous Tests are on Travis, see [instruction](https://github.ibm.com/was-liberty/openliberty-guides-team/wiki/Automation-Tests-For-OpenLiberty-Guides#setup-travis-ci-tests-for-openliberty-guides) 
- [x] Enable pull creation notification on the repo for `was-lib-guides-alerts`, see [instruction](https://github.ibm.com/was-liberty/openliberty-guides-team/wiki/Automation-Tests-For-OpenLiberty-Guides#subscribing-static-guides-repositories-to-a-slack-channel)
- [x] Enable `master` and `qa` branches lock down, see [instruction](https://github.ibm.com/was-liberty/openliberty-guides-team/wiki/Automation-Tests-For-OpenLiberty-Guides#setup-travis-ci-tests-for-openliberty-guides) 
- [x] Add the new guide's repo to the `OpenLiberty/guides-common` ZenHub board
- [x] Delete `dev` branch
- [x] (Optional) Send announcement to slack channel(s)

- [x] Arrange a demo at the EOI meeting

**Comment by NimG98** [comment]
**Defining a component to consume a service**:

- Similar sentences are repeated:

    First sentence:
    > `AppComponent` implements `OnInit`, which is a special interface called a lifecycle hook.
    Last sentence:
    > The `AppComponent` class implements the `OnInit` interface.

**Comment by NimG98** [comment]
UI Issue with safari:

- sometimes randomly after scrolling up and down, a copy icon appears at the title


![image](https://user-images.githubusercontent.com/46586499/59950639-887b9c00-9444-11e9-92ae-d5fe05cbe6fa.png)

**Comment by evelinec** [comment]
Note, need to delete the `dev` branch protection rule before you can delete this branch.

**Comment by evelinec** [comment]
Opened https://github.com/OpenLiberty/openliberty.io/issues/1234 to UI team to handle this UI issue.

**Comment by NimG98** [comment]
UI Issue: https://github.com/OpenLiberty/openliberty.io/issues/1233

**Comment by evelinec** [comment]
Completed.
