### ISSUE TITLE
The app root URL is not accessible with curl

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guide-rest-client-angular#42]
On Linux and Windows, running the `mvn generate-resources` command to build the front end had the follow error:
```
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[ERROR] 
[INFO] added 1099 packages from 1028 contributors and audited 43177 packages in 32.881s
[INFO] found 12 vulnerabilities (1 low, 1 moderate, 10 high)
[INFO]   run `npm audit fix` to fix them, or `npm audit` for details
```

Accessing the web app root `http://localhost:9080/app` from a browser shows the correct result. But this URL is not accessible via the `curl` command. It gives the 302 code. This happens on both Mac and Linux. This issue happens with the original app; it's not to do with dev mode conversion.

**Comment by realModusOperandi** [comment]
I think this is something Liberty is doing. If I curl the exact URL with verbose output, I get:
```
[root@feros-icpboot start]# curl -v http://localhost:9080/app
* About to connect() to localhost port 9080 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 9080 (#0)
> GET /app HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:9080
> Accept: */*
>
< HTTP/1.1 302 Found
< X-Powered-By: Servlet/4.0
< Location: http://localhost:9080/app/
< Content-Language: en-US
< Transfer-Encoding: chunked
< Date: Mon, 02 Dec 2019 20:25:53 GMT
<
* Connection #0 to host localhost left intact
```
. HTTP 302 is intended as a redirect response, which indicates that Servlet-4.0 in Liberty is redirecting me to `http://localhost:9080/app/` (note the trailing /). Browsers display this correctly because the interpret the 302 as a redirect and access the value of the `Location` field in the response. Directly `curl`ing the value of that field gets me the contents of index.html as I would expect, as does instructing `curl` to follow redirects via the `-L` option:

```
[root@feros-icpboot start]# curl -v -L http://localhost:9080/app
* About to connect() to localhost port 9080 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 9080 (#0)
> GET /app HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:9080
> Accept: */*
>
< HTTP/1.1 302 Found
< X-Powered-By: Servlet/4.0
< Location: http://localhost:9080/app/
< Content-Language: en-US
< Transfer-Encoding: chunked
< Date: Mon, 02 Dec 2019 20:44:14 GMT
<
* Ignoring the response-body
* Connection #0 to host localhost left intact
* Issue another request to this URL: 'http://localhost:9080/app/'
* Found bundle for host localhost: 0x20ccee0
* Re-using existing connection! (#0) with host localhost
* Connected to localhost (::1) port 9080 (#0)
> GET /app/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:9080
> Accept: */*
>
< HTTP/1.1 200 OK
< X-Powered-By: Servlet/4.0
< Date: Mon, 02 Dec 2019 20:44:14 GMT
< Content-Type: text/html
< Last-Modified: Mon, 02 Dec 2019 20:23:59 GMT
< Content-Length: 655
< Content-Language: en-US
<
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Frontend</title>
  <base href="/app/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
</head>
<body>
  <app-root></app-root>
<script type="text/javascript" src="runtime.js"></script><script type="text/javascript" src="es2015-polyfills.js" nomodule></script><script type="text/javascript" src="polyfills.js"></script><script type="text/javascript" src="styles.js"></script><script type="text/javascript" src="vendor.js"></script><script type="text/javascript" src="main.js"></script></body>
</html>
* Connection #0 to host localhost left intact
```

I'll make sure any instructions in the guide to `curl` the app include the trailing slash. We may want to consult with the OpenLiberty people in charge of the web container if this behavior is not desired.

**Comment by evelinec** [comment]
This guide doesn't use the `curl` command to visit the application root URL. It was used as part of guide's verification steps. When using `curl` to visit the application root URL, ie, `curl http://localhost:9080/app/`, user will see the `index.html` content but not the consumed data (as seen on a web browser). As @realModusOperandi explained, we could emphasize that the job of the Angular framework is to use JavaScript to completely change the HTML to display the application, so javascript is essential to having a working page. This can be added to the guide for clarification. 

As with the additional / that's needed in the app root URL, we can open an issue in openliberty.

**Comment by evelinec** [comment]
Added a paragraph to clarify using `curl` command to visit the application root URL in https://github.com/OpenLiberty/guide-rest-client-angular/pull/40/commits/7649ffab45a511bd835337c4c11d0333f5ca7001. @realModusOperandi would you take a look? Thank you.

**Comment by evelinec** [comment]
Checked with Liam for the added paragraph in this guide. Thank you @realModusOperandi
