### ISSUE TITLE
Address security advisory for kind-of and minimist

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-rest-client-angular#57]
https://github.com/OpenLiberty/guide-rest-client-angular/network/alerts

**Comment by gkwan-ibm** [comment]
@realModusOperandi would you able to fix this?

**Comment by realModusOperandi** [comment]
Minimist is not used for anything in the guide so I dismissed that one.

**Comment by DannyS03** [comment]
Addressed: https://github.com/OpenLiberty/guide-rest-client-angular/pull/60.
