### ISSUE TITLE
Quick peer review - Windows

### ISSUE THREAD

**Issue by TiagoF99** [OpenLiberty/guide-rest-client-angular#65]
- end-2-end, hotspot, typo

**Comment by TiagoF99** [comment]
**What You'll Learn**
- [ ] ```but you only need to edit only a few to consume the REST service and display its data.``` should be ```but you only need to edit a few to consume the REST service and display its data.```

**Other**
- [ ] i think it would be convenient to note ```nodejs``` and ```angularCli``` as pre requisities. 
- [ ] Building the front end and testing the angular client both seem really similar and it seems like they might be able to be combined into one header/section

**Comment by DannyS03** [comment]
Thank you for the feedback, @TiagoF99.
-  What do you mean by they both had to be installed? 
> I think it would be convenient to note nodejs and angularCli as pre requisities as they both had to be installed. Maybe a prereq section can be added like in other guides with docker?

- I see what you mean. The difference with this guide is that it does not focus necessarily on testing the application, though the testing section is generic across the guides. In this case, the testing section serves as information.
>  Building the front end and testing the angular client both seem really similar and it seems like they might be able to be combined into one header/section

-  The **start** directory was just missing the dependencies in the **package.json** & **package-lock.json** for `@angular/platform-browser` and `@angular/core` as I hadn't pushed the updated files. It can be tested again.

**Comment by TiagoF99** [comment]
@DannyS03 
- I meant that when running ```mvn generate-resources```, an ```ng``` command failed because I didnt have it installed. I had to install node so i could get npm and then I had to npm install angularCli to get the ng command to work. It was a setup issue for me though I think it could be worthy to state that both nodejs and angularCli should be installed for anyone who may be new to angular and who wants to go through our guide. 
- I think for the second point that it may be redundant to include: ```You can rebuild only your Angular front end by running the following command:``` and the corresponding command though, as it is also stated in the section before. I think the rest of the test section has good and helpful content though
- I will test the new changes now

**Comment by DannyS03** [comment]
- Ah I see what you mean. I believe your issue wasn't because of the environment though (it was because there were missing frontend angular dependencies in the start dir) as the application is configured to install a copy of node locally. The angular configuration is just defined in the packages that node will execute (the scripts). 

Right, good point. Updated. 
> I think for the second point that it may be redundant to include: ```You can rebuild only your Angular front end by running the following command:``` and the corresponding command though, as it is also stated in the section before. I think the rest of the test section has good and helpful content though

**Comment by TiagoF99** [comment]
Yeah you are right, everything looks good now.
