### ISSUE TITLE
Quick peer review - Linux

### ISSUE THREAD

**Issue by griffinhadfield** [OpenLiberty/guide-rest-client-angular#66]

**Comment by griffinhadfield** [comment]
- [ ] In **What you’ll learn**, it seems like the below sentence has a grammar error at the end. I don’t think the “the” should be there.

> The REST service that provides the artists and albums resource was written for you in advance and responds with the artists.json.

- [ ] When running `mvn generate-resources`, I get the below error. It is fixed when I run `npm install` in `/src/main/frontend`. Should this be added as a script somewhere or maybe included as an instruction? 

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/38739044/84690936-48dd7800-af11-11ea-977e-a0e2f02b3fa3.png">

**Comment by DannyS03** [comment]
Thanks for the feedback, @griffinhadfield. 
- For the grammar error, the sentence was originally written in this way and generalizes the content in the file by just stating the file itself, though saying "object s in..." would work too. I just left it as is for now and if it comes up in the ID review we can change it. 

-  The **start** directory was just missing the dependencies in the **package.json** & **package-lock.json** for `@angular/platform-browser` and `@angular/core` as I hadn't pushed the updated files. It can be tested again.

**Comment by DannyS03** [comment]
- re-added configuration to install copy of node on linux env. 
```
                    <execution>
                        <id>npm install</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <!-- Optional configuration which provides for running any npm command -->
                        <configuration>
                            <arguments>install</arguments>
                        </configuration>
                    </execution>
```

**Comment by griffinhadfield** [comment]
Looks good. Ran another end-to-end test and everything works. Closing this issue
