### ISSUE TITLE
Quick peer review - Mac

### ISSUE THREAD

**Issue by jj-zhang** [OpenLiberty/guide-rest-client-angular#67]

**Comment by jj-zhang** [comment]
#### Project Configuration

- [ ] `Node.js is a JavaScript runtime` should add `environment` at the end.

**Comment by DannyS03** [comment]
> #### Project Configuration
> 
>     * [ ]  `Node.js is a JavaScript runtime` should be `Node.js is a JavaScript runtime environment`.

I updated it to 
```
Node.js is server-side JavaScript runtime that is used for developing networking applications.
```

which is like the reactjs guide.

**Comment by jj-zhang** [comment]
Looks cool!
